const API_URL=(window.APP_CONFIG&&window.APP_CONFIG.API_URL)||'';
const state={role:'',className:'',apiKey:'',data:{summary:{},records:[],students:[],books:[],tasks:[]},page:'dashboard',editing:null,reviewing:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>v?new Date(v).toLocaleDateString('zh-TW'):'—';
const statusText={pending:'待審核',approved:'已通過',rejected:'已退回',active:'進行中',closed:'已結束'};

document.addEventListener('DOMContentLoaded',()=>{bind();restoreSession();});
function bind(){
 $('#loginRole').addEventListener('change',()=>$('#classField').hidden=$('#loginRole').value==='admin');
 $('#loginForm').addEventListener('submit',login);
 $('#logoutButton').addEventListener('click',logout); $('#refreshData').addEventListener('click',loadAll);
 $$('.nav-item').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
 $$('[data-jump]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.jump)));
 $('#sidebarToggle').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
 $('#reviewFilterButton').addEventListener('click',renderReviews); $('#recordFilterButton').addEventListener('click',renderRecords);
 $('#newTaskButton').addEventListener('click',()=>openEditor('task'));
 $('#newRecordButton').addEventListener('click',()=>openEditor('record'));
 $('#newStudentButton').addEventListener('click',()=>openEditor('student'));
 $('#newBookButton').addEventListener('click',()=>openEditor('book'));
 $('#dialogClose').addEventListener('click',closeEditor); $('#dialogCancel').addEventListener('click',closeEditor); $('#editForm').addEventListener('submit',saveEditor);
 $$('[data-close-review]').forEach(b=>b.addEventListener('click',()=>$('#reviewDialog').close()));
 $('#reviewForm').addEventListener('submit',e=>{e.preventDefault();reviewAction('approved')}); $('#rejectReview').addEventListener('click',()=>reviewAction('rejected'));
 $$('[data-export]').forEach(b=>b.addEventListener('click',()=>exportCsv(b.dataset.export)));
}
function restoreSession(){try{const s=JSON.parse(sessionStorage.getItem('rp-admin')||'null');if(s){Object.assign(state,s);enterApp();}}catch(e){}}
async function login(e){e.preventDefault();state.role=$('#loginRole').value;state.className=$('#loginClass').value.trim();state.apiKey=$('#loginKey').value.trim();if(state.role==='teacher'&&!state.className)return showLoginError('請輸入管理班級');try{const r=await api('login',{role:state.role,className:state.className,apiKey:state.apiKey});state.className=r.className||state.className;sessionStorage.setItem('rp-admin',JSON.stringify({role:state.role,className:state.className,apiKey:state.apiKey}));enterApp();}catch(err){showLoginError(err.message)}}
function showLoginError(t){$('#loginError').textContent=t}
function logout(){sessionStorage.removeItem('rp-admin');location.reload()}
function enterApp(){$('#loginView').hidden=true;$('#appView').hidden=false;$$('.admin-only').forEach(x=>x.hidden=state.role!=='admin');$('#userBadge').innerHTML=`<strong>${state.role==='admin'?'系統管理者':'班級教師'}</strong><small>${esc(state.role==='admin'?'全校管理':state.className)}</small>`;$('#taskScopeHint').textContent=state.role==='admin'?'可指定全年級或特定班級閱讀任務，完成並審核後計入篇數。':`僅可指定 ${state.className} 學生閱讀任務，完成並審核後計入篇數。`;loadAll()}
async function api(action,payload={}){if(!API_URL)throw new Error('尚未在 config.js 設定 API_URL');const body={action,role:state.role,className:state.className,apiKey:state.apiKey,...payload};const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const json=await res.json();if(!json.success)throw new Error(json.message||'操作失敗');return json.data}
async function loadAll(){try{toast('資料載入中…');state.data=await api('getManagementData');renderAll();toast('資料已更新')}catch(e){toast(e.message,true)}}
function renderAll(){renderDashboard();renderReviews();renderTasks();renderRecords();renderStudents();renderBooks()}
function showPage(page){state.page=page;$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const names={dashboard:['管理儀表板','掌握閱讀成果與待辦事項'],reviews:['心得審核','審核學生閱讀心得並給予回饋'],tasks:['閱讀任務','指定書籍、期限與心得要求'],records:['閱讀資料','編修全校閱讀紀錄'],students:['學生管理','維護學生與班級資料'],books:['書籍管理','維護指定閱讀書目'],exports:['資料匯出','下載管理資料 CSV']};$('#pageTitle').textContent=names[page][0];$('#pageSubtitle').textContent=names[page][1];$('.sidebar').classList.remove('open')}
function renderDashboard(){const s=state.data.summary||{};const cards=[['公開心得',s.approved||0,'已核准並計入篇數'],['待審核',s.pending||0,'需要教師處理'],['進行任務',s.activeTasks||0,'指定閱讀作業'],['累積頁數',(s.totalPages||0).toLocaleString(),'已通過閱讀紀錄']];$('#statCards').innerHTML=cards.map(x=>`<article class="stat-card"><span class="label">${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');const pending=state.data.records.filter(r=>r.status==='pending').slice(0,5);$('#pendingPreview').innerHTML=pending.length?pending.map(r=>`<div class="compact-item"><div><strong>${esc(r.studentName)} · ${esc(r.bookTitle)}</strong><p>${esc((r.reviewSummary||r.reviewContent||'').slice(0,42))}</p></div><small>${fmtDate(r.createdAt)}</small></div>`).join(''):'<p>目前沒有待審核心得。</p>';const tasks=state.data.tasks.filter(t=>t.status==='active').slice(0,5);$('#taskPreview').innerHTML=tasks.length?tasks.map(t=>`<div class="compact-item"><div><strong>${esc(t.title)}</strong><p>${esc(t.scopeLabel)} · ${esc(t.bookTitle)}</p></div><small>${t.completedCount||0} 篇</small></div>`).join(''):'<p>目前沒有進行中的任務。</p>'}
function renderReviews(){const q=$('#reviewSearch').value.trim().toLowerCase(),st=$('#reviewStatus').value;let rows=state.data.records.filter(r=>(st==='all'||r.status===st)&&(!q||[r.studentName,r.bookTitle,r.reviewContent,r.className].join(' ').toLowerCase().includes(q)));$('#reviewTable').innerHTML=rows.length?rows.map(r=>`<tr><td><strong>${esc(r.studentName)}</strong><br><small>${esc(r.className)}</small></td><td><strong>${esc(r.bookTitle)}</strong><br><small>${r.taskId?'指定任務':'自由閱讀'}</small></td><td>${esc((r.reviewSummary||r.reviewContent||'').slice(0,70))}</td><td>${r.status==='approved'?'已累積 1 篇':'尚未計入'}</td><td><span class="status ${esc(r.status)}">${statusText[r.status]||r.status}</span></td><td><div class="row-actions"><button onclick="openReview('${r.recordId}')">查看／審核</button></div></td></tr>`).join(''):'<tr><td colspan="6">查無資料</td></tr>'}
function renderTasks(){const rows=state.data.tasks;$('#taskCards').innerHTML=rows.length?rows.map(t=>{const pct=t.targetCount?Math.min(100,Math.round((t.completedCount||0)/t.targetCount*100)):0;return `<article class="task-card"><span class="task-scope">${esc(t.scopeLabel)}</span><h3>${esc(t.title)}</h3><strong>${esc(t.bookTitle)}</strong><p>${esc(t.description||'完成閱讀並撰寫心得。')}</p><div class="task-progress"><i style="width:${pct}%"></i></div><div class="task-meta"><span>${t.completedCount||0} 篇完成</span><span>期限 ${fmtDate(t.dueDate)}</span></div><div class="task-actions"><button onclick="openEditor('task','${t.taskId}')">編輯</button><button onclick="removeItem('task','${t.taskId}')">刪除</button></div></article>`}).join(''):'<p>尚未建立閱讀任務。</p>'}
function renderRecords(){if(state.role!=='admin')return;const q=$('#recordSearch').value.trim().toLowerCase(),st=$('#recordStatus').value;let rows=state.data.records.filter(r=>(st==='all'||r.status===st)&&(!q||[r.studentName,r.bookTitle,r.className].join(' ').toLowerCase().includes(q)));$('#recordTable').innerHTML=rows.map(r=>`<tr><td>${fmtDate(r.createdAt)}</td><td>${esc(r.studentName)}<br><small>${esc(r.className)}</small></td><td>${esc(r.bookTitle)}</td><td>${r.pages||0}</td><td>${r.taskId?'任務':'自由閱讀'}</td><td><span class="status ${r.status}">${statusText[r.status]||r.status}</span></td><td><div class="row-actions"><button onclick="openEditor('record','${r.recordId}')">編輯</button><button onclick="removeItem('record','${r.recordId}')">刪除</button></div></td></tr>`).join('')||'<tr><td colspan="7">查無資料</td></tr>'}
function renderStudents(){if(state.role!=='admin')return;$('#studentTable').innerHTML=state.data.students.map(s=>`<tr><td>${esc(s.studentId)}</td><td>${esc(s.studentName)}</td><td>${esc(s.grade)}</td><td>${esc(s.className)}</td><td>${String(s.active)!=='false'?'啟用':'停用'}</td><td><div class="row-actions"><button onclick="openEditor('student','${s.studentId}')">編輯</button><button onclick="removeItem('student','${s.studentId}')">刪除</button></div></td></tr>`).join('')||'<tr><td colspan="6">尚無學生資料</td></tr>'}
function renderBooks(){if(state.role!=='admin')return;$('#bookTable').innerHTML=state.data.books.map(b=>`<tr><td>${esc(b.isbn)}</td><td>${esc(b.bookTitle)}</td><td>${esc(b.author)}</td><td>${esc(b.category)}</td><td>${b.pages||0}</td><td><div class="row-actions"><button onclick="openEditor('book','${b.bookId}')">編輯</button><button onclick="removeItem('book','${b.bookId}')">刪除</button></div></td></tr>`).join('')||'<tr><td colspan="6">尚無書籍資料</td></tr>'}
window.openReview=function(id){const r=state.data.records.find(x=>String(x.recordId)===String(id));if(!r)return;state.reviewing=r;$('#reviewDetail').innerHTML=`<p><strong>${esc(r.studentName)}</strong>｜${esc(r.className)}｜${esc(r.bookTitle)}</p><p>${r.taskId?'指定閱讀任務':'自由閱讀'} · ${r.pages||0} 頁</p><div class="review-content">${esc(r.reviewContent||'（未填寫心得內容）').replace(/\n/g,'<br>')}</div>`;$('#reviewFeedback').value=r.teacherFeedback||'';$('#reviewDialog').showModal()}
async function reviewAction(status){try{await api('reviewRecord',{recordId:state.reviewing.recordId,status,teacherFeedback:$('#reviewFeedback').value});$('#reviewDialog').close();await loadAll();toast(status==='approved'?'已通過，心得篇數已累積':'已退回學生修改')}catch(e){toast(e.message,true)}}
const fieldDefs={task:[['title','任務名稱','text'],['scopeType','指定範圍','select','grade:全年級|class:特定班級'],['scopeValue','年級／班級','text'],['bookTitle','指定書籍','text'],['isbn','ISBN','text'],['description','心得要求','textarea'],['dueDate','截止日期','date'],['targetCount','預計完成篇數','number'],['status','任務狀態','select','active:進行中|closed:已結束']],record:[['studentId','學號','text'],['studentName','學生姓名','text'],['grade','年級','text'],['className','班級','text'],['bookTitle','書名','text'],['isbn','ISBN','text'],['pages','頁數','number'],['reviewContent','心得內容','textarea'],['status','狀態','select','pending:待審核|approved:已通過|rejected:已退回'],['isPublic','公開前台','select','true:是|false:否']],student:[['studentId','學號','text'],['studentName','姓名','text'],['grade','年級','text'],['className','班級','text'],['active','狀態','select','true:啟用|false:停用']],book:[['bookId','書籍編號','text'],['isbn','ISBN','text'],['bookTitle','書名','text'],['author','作者','text'],['category','分類','text'],['pages','頁數','number']]};
window.openEditor=function(type,id=''){state.editing={type,id};const list=type==='task'?state.data.tasks:type==='record'?state.data.records:type==='student'?state.data.students:state.data.books;const key={task:'taskId',record:'recordId',student:'studentId',book:'bookId'}[type],item=list.find(x=>String(x[key])===String(id))||{};$('#dialogTitle').textContent=(id?'編輯':'新增')+({task:'閱讀任務',record:'閱讀紀錄',student:'學生資料',book:'書籍資料'}[type]);$('#dialogEyebrow').textContent=type.toUpperCase();$('#dialogFields').innerHTML=fieldDefs[type].map(([name,label,kind,opts])=>{const val=item[name]??(type==='task'&&name==='scopeType'?(state.role==='teacher'?'class':'grade'):'');const wide=kind==='textarea'?'wide':'';if(kind==='select')return `<label class="${wide}">${label}<select name="${name}">${opts.split('|').map(o=>{const [v,t]=o.split(':');return `<option value="${v}" ${String(val)===v?'selected':''}>${t}</option>`}).join('')}</select></label>`;return `<label class="${wide}">${label}${kind==='textarea'?`<textarea name="${name}" rows="5">${esc(val)}</textarea>`:`<input name="${name}" type="${kind}" value="${esc(kind==='date'&&val?String(val).slice(0,10):val)}">`}</label>`}).join('');if(type==='task'&&state.role==='teacher'){const st=$('[name="scopeType"]');st.value='class';st.disabled=true;$('[name="scopeValue"]').value=state.className;$('[name="scopeValue"]').readOnly=true}$('#editDialog').showModal()}
function closeEditor(){$('#editDialog').close()}
async function saveEditor(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());if(state.editing.type==='task'&&state.role==='teacher'){data.scopeType='class';data.scopeValue=state.className}try{await api('saveEntity',{entity:state.editing.type,id:state.editing.id,data});closeEditor();await loadAll();toast('資料已儲存')}catch(err){toast(err.message,true)}}
window.removeItem=async function(entity,id){if(!confirm('確定刪除此筆資料？此動作無法復原。'))return;try{await api('deleteEntity',{entity,id});await loadAll();toast('資料已刪除')}catch(e){toast(e.message,true)}}
function exportCsv(type){
 const rows=type==='records'?state.data.records:type==='students'?state.data.students:state.data.tasks;
 if(!rows.length)return toast('沒有可匯出的資料',true);
 const names={records:'閱讀紀錄',students:'學生資料',tasks:'閱讀任務'};
 const date=new Date().toISOString().slice(0,10);
 if(window.XLSX){
   const ws=XLSX.utils.json_to_sheet(rows);
   const wb=XLSX.utils.book_new();
   XLSX.utils.book_append_sheet(wb,ws,names[type]);
   XLSX.writeFile(wb,`閱讀護照-${names[type]}-${date}.xlsx`);
   return toast('Excel 檔案已匯出');
 }
 const keys=Object.keys(rows[0]);
 const csv='\ufeff'+[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(','))].join('\n');
 const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`reading-${type}-${date}.csv`;a.click();URL.revokeObjectURL(a.href);
 toast('Excel 元件未載入，已改匯出 CSV');
}
function toast(t,bad=false){const el=$('#toast');el.textContent=t;el.style.background=bad?'#9f3e35':'#17333a';el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
